name: Pull Jenkins action from ECR and build jenkins job

on:
  push:
    branches:
      - main

jobs:
  pull-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Pull jenkins action image from ECR
        run: |
          aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 641518622681.dkr.ecr.us-west-2.amazonaws.com
          docker pull 641518622681.dkr.ecr.us-west-2.amazonaws.com/cbactions-ext-jenkins-actions:latest
          docker run -e PARAMETER='{"key": "value"}' 641518622681.dkr.ecr.us-west-2.amazonaws.com/cbactions-ext-jenkins-actions:latest 
